global:
  scrape_interval: 15s
  evaluation_interval: 30s
  scrape_timeout: 10s
  external_labels:
    monitor: vllm-observability
    env: prod

rule_files:
  - /etc/prometheus/recording_rules.yml
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: vllm
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - <REMOTE_VLLM_HOST_OR_IP>:8000
        labels:
          service: vllm
          component: inference
          env: prod
          stack: vllm-observability
          instance_name: gpt-oss-120b-a

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
        labels:
          service: prometheus
          component: monitoring
          env: prod
          stack: vllm-observability